# Default values 

installCrd: true # if installing both controller and env injector, only one can install CRD
image:
  repository: spvest/azure-keyvault-controller
  tag: 0.1.0

keyVault:
  # Set to true to use custom auth - see https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/README.md#authentication 
  customAuth:
    enabled: false

    # Uncomment to use aad-pod-identity (MSI) and point to a selector
    # podIdentitySelector: azure-key-vault

  polling:
    normalInterval: 1m
    failureInterval: 10m
    failureAttempts: 5

logLevel: info
cloudConfig: /etc/kubernetes/azure.json