# Default values 

installCrd: true # if installing both controller and env injector, only one can install CRD
replicaCount: 2

image:
  repository: spvest/azure-keyvault-webhook
  tag: 1.1.0-beta.24
  pullPolicy: IfNotPresent

envImage:
  repository: spvest/azure-keyvault-env
  tag: 1.1.0-beta.24

keyVault:
  # Set to true to use custom auth - see https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/README.md#authentication
  customAuth:
    enabled: false

    # uncomment to use aad-pod-identity (MSI) and point to a selector
    # if used, secretName must not be set
    # podIdentitySelector: <selector name>

authService:
  enabled: true
  logLevel: Info
  image:
    repository: spvest/azure-keyvault-auth-service
    tag: 1.1.0-beta.24
  port:
    name: azure-keyvault-secrets-auth
    externalPort: 8443
    internalPort: 8443
  clientCertSecretName: akv2k8s-client-cert
  cloudConfigHostPath: /etc/kubernetes/azure.json

service:
  name: azure-keyvault-secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 443

metrics:
  enabled: false
  metricsAddress: ":80"

webhook:
  logLevel: Info
  dockerPullTimeout: 120 # will timeout after 120 seconds 

  # What will happen if the webhook fails? Ignore (continue) or Fail (prevent Pod from starting)?
  failurePolicy: Ignore

  # https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
  namespaceSelector:
    matchLabels:
      azure-key-vault-env-injection: enabled # The webhook will only trigger i namespaces with this label

    # Prevent env injection for pods in kube-system as recomended: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-operating-on-the-kube-system-namespace
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - kube-system

## See `kubectl explain poddisruptionbudget.spec` for more
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
podDisruptionBudget:
  enabled: true
  minAvailable: 1
#  maxUnavailable: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}