name: public release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      
    - name: Docker Pull
      run: |
        docker login -u ${{secrets.PRIVATE_REGISTRY_USERNAME}} -p ${{secrets.PRIVATE_REGISTRY_PASSWORD}} dokken.azurecr.io
        make pull-release

    - name: Docker Push
      run: |
        docker login -u ${{secrets.PUBLIC_REGISTRY_USERNAME}} -p ${{secrets.PUBLIC_REGISTRY_PASSWORD}}
        make release DOCKER_RELEASE_TAG={{github.ref}}
        